server.port=8080

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false


logging.level.com.paul9834=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.org.springframework.cache=INFO

app.security.jwt.secret=${JWT_SECRET}
app.security.jwt.expiration-hours=${JWT_EXPIRATION_HOURS:8760}
app.security.admin.password=${ADMIN_PASSWORD}

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
